# v2 sintax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  moodle-mysql-data:
    driver: local

services:
  # MySQL
  mysql-moodle:
    image: ambientum/mysql:5.7
    container_name: moodle-mysql
    volumes:
      - moodle-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle

  # PHP
  app-moodle:
    image: my-moodle-image
    container_name: moodle-web
    volumes:
      - .:/var/www/html
      - .:/var/www/moodledata
    ports:
      - "80:80"
    links:
      - mysql-moodle
